name: Compile and Verify

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
     
    steps:
      - uses: actions/checkout@v1
       
      - name: install perl lint
        run: sudo apt install libb-lint-perl
        
      #Run perl5 script to verify file sizies in controls_xxx.txt files      
      - name: verify controls_xxx.txt files
        run: |
          perl test/controls.pl
          
      #Compile
      - name: compile 00_TronfernoMCU.pm
        run:
          make 00_TronfernoMCU.compile  
      #Compile
      - name: compile 10_Tronferno.pm
        run:
          make 10_Tronferno.compile
      #Compile
      - name: compile 10_Fernotron.pm
        run:
          make 10_Fernotron.compile
          